Job description file for data export
Ellie Fewings; 21Dec17

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap2.medschl.cam.ac.uk
Project location: /share/user/path_to_results_folder

project: project
vep annotated dataset: set1_vqsr_std_sma_ann

======================= HPC settings ========================

working_folder: /rds/project/erf33/rds-erf33-medgen/users

Account to use on HPC: TISCHKOWITZ-SL2-CPU
Max time to request (hrs.min.sec): 01.00.00

==================== Pipeline summary ======================

# Export selected tables from vep-vcf to txt files
#
# Exported tables:
#
# VCF_VEP annotations
# 1k and Exac annotations
# GT: Alphabetically coded genotype
# GT add, dom, rec: Numerically coded genotypes for additive, dominant and recessive models (biallelic only) 
# DP: Approximate read depth (reads with MQ=255 or with bad mates are filtered)
# AD: Allelic depths for the ref and alt alleles in the order listed
# GQ: Genotype Quality
# PL: Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification
#
# Examples of not exported tables (scarce or not needed data): 
#
# SB: Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.
# RGQ: Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)
# MIN_DP: Minimum DP observed within the GVCF block
# PGT: Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another
# PID: Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group

===================== Standard settings =====================

#Use script "p08A_wes_export_txt" for 10 samples or less
scripts_folder: /rds/project/erf33/rds-erf33-medgen/scripts/wes_pipeline_01.18/p08_wes_export_txt
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /rds/project/erf33/rds-erf33-medgen/tools
java: java/jre1.8.0_40/bin/java
gatk: gatk/gatk-3.6-0/GenomeAnalysisTK.jar

r_bin_folder: r/R-3.3.2/bin/
r_lib_folder: r/R-3.3.2/lib64/R/library

Note about requirements for R 
-----------------------------
R is used here to genereate html and pdf reports with rmarkdown.
Generating reports with Rmarkdown is pernickety about environment. 
It requires recent versions of several system libraries
and a number of internal R libraries to be pre-installed.
The external libraries are loaded as modules in *.sb.sh script:
module load gcc/5.2.0
module load boost/1.50.0
module load texlive/2015
module load pandoc/1.15.2.1
List of internal r-libraries is in the r-installation notes.
rmarkdown library has to be installed in the r_lib_folder
shown above.

Resources
---------

resources_folder: /rds/project/erf33/rds-erf33-medgen/resources

decompressed_bundle_folder: gatk_bundle/b37/decompressed
ref_genome: human_g1k_v37.fasta

targets_folder: illumina_nextera
targets_intervals: nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals

Additional settings
-------------------

VEP fields: SYMBOL|Allele|Existing_variation|Consequence|IMPACT|CLIN_SIG|SIFT|PolyPhen|cDNA_position|CDS_position|Codons|Protein_position|Amino_acids|DISTANCE|STRAND|SYMBOL_SOURCE
